// --- Transcript Types ---

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface TranscriptResult {
  segments: TranscriptSegment[];
  languageCode: string;
  isAutoGenerated: boolean;
}

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name: string;
}

export interface Chapter {
  title: string;
  startTime: number;
  endTime: number;
}

export interface LanguageInfo {
  code: string;
  name: string;
  isAutoGenerated: boolean;
}

// --- Transcript Errors ---

export class TranscriptNotAvailableError extends Error {
  constructor(videoId: string) {
    super(`No caption tracks available for video: ${videoId}`);
    this.name = "TranscriptNotAvailableError";
  }
}

export class TranscriptDisabledError extends Error {
  constructor(videoId: string) {
    super(`Captions are disabled for video: ${videoId}`);
    this.name = "TranscriptDisabledError";
  }
}

export class VideoNotFoundError extends Error {
  constructor(videoId: string) {
    super(`Video not found or unavailable: ${videoId}`);
    this.name = "VideoNotFoundError";
  }
}

export class TranscriptFetchError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TranscriptFetchError";
  }
}

// --- YouTube Data API Types ---

export interface YouTubeApiError {
  code: number;
  message: string;
  errors: Array<{ domain: string; reason: string; message: string }>;
}

export interface YouTubePageInfo {
  totalResults: number;
  resultsPerPage: number;
}

export interface YouTubeThumbnail {
  url: string;
  width: number;
  height: number;
}

export interface YouTubeThumbnails {
  default?: YouTubeThumbnail;
  medium?: YouTubeThumbnail;
  high?: YouTubeThumbnail;
  standard?: YouTubeThumbnail;
  maxres?: YouTubeThumbnail;
}

export interface VideoSnippet {
  publishedAt: string;
  channelId: string;
  title: string;
  description: string;
  thumbnails: YouTubeThumbnails;
  channelTitle: string;
  tags?: string[];
  categoryId?: string;
}

export interface VideoContentDetails {
  duration: string;
  dimension: string;
  definition: string;
  caption: string;
}

export interface VideoStatistics {
  viewCount: string;
  likeCount: string;
  commentCount: string;
}

export interface VideoResource {
  kind: string;
  id: string;
  snippet?: VideoSnippet;
  contentDetails?: VideoContentDetails;
  statistics?: VideoStatistics;
}

export interface VideoListResponse {
  kind: string;
  pageInfo: YouTubePageInfo;
  items: VideoResource[];
}

export interface SearchResultSnippet {
  publishedAt: string;
  channelId: string;
  title: string;
  description: string;
  thumbnails: YouTubeThumbnails;
  channelTitle: string;
}

export interface SearchResultId {
  kind: string;
  videoId?: string;
  channelId?: string;
  playlistId?: string;
}

export interface SearchResult {
  kind: string;
  id: SearchResultId;
  snippet: SearchResultSnippet;
}

export interface SearchListResponse {
  kind: string;
  nextPageToken?: string;
  prevPageToken?: string;
  pageInfo: YouTubePageInfo;
  items: SearchResult[];
}

export interface ChannelSnippet {
  title: string;
  description: string;
  customUrl?: string;
  publishedAt: string;
  thumbnails: YouTubeThumbnails;
  country?: string;
}

export interface ChannelStatistics {
  viewCount: string;
  subscriberCount: string;
  hiddenSubscriberCount: boolean;
  videoCount: string;
}

export interface ChannelBrandingSettings {
  channel?: {
    title?: string;
    description?: string;
    keywords?: string;
    unsubscribedTrailer?: string;
  };
  image?: {
    bannerExternalUrl?: string;
  };
}

export interface ChannelContentDetails {
  relatedPlaylists: {
    uploads: string;
  };
}

export interface ChannelResource {
  kind: string;
  id: string;
  snippet?: ChannelSnippet;
  statistics?: ChannelStatistics;
  brandingSettings?: ChannelBrandingSettings;
  contentDetails?: ChannelContentDetails;
}

export interface ChannelListResponse {
  kind: string;
  pageInfo: YouTubePageInfo;
  items: ChannelResource[];
}

export interface PlaylistSnippet {
  publishedAt: string;
  channelId: string;
  title: string;
  description: string;
  thumbnails: YouTubeThumbnails;
  channelTitle: string;
  itemCount?: number;
}

export interface PlaylistResource {
  kind: string;
  id: string;
  snippet?: PlaylistSnippet;
  contentDetails?: {
    itemCount: number;
  };
}

export interface PlaylistListResponse {
  kind: string;
  nextPageToken?: string;
  pageInfo: YouTubePageInfo;
  items: PlaylistResource[];
}

export interface PlaylistItemSnippet {
  publishedAt: string;
  channelId: string;
  title: string;
  description: string;
  thumbnails: YouTubeThumbnails;
  channelTitle: string;
  resourceId: {
    kind: string;
    videoId: string;
  };
}

export interface PlaylistItemContentDetails {
  videoId: string;
  videoPublishedAt: string;
}

export interface PlaylistItem {
  kind: string;
  snippet: PlaylistItemSnippet;
  contentDetails?: PlaylistItemContentDetails;
}

export interface PlaylistItemListResponse {
  kind: string;
  nextPageToken?: string;
  pageInfo: YouTubePageInfo;
  items: PlaylistItem[];
}
