import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { TranscriptFetcher } from "../utils/transcript-fetcher.js";
import { filterAdSegments } from "../utils/ad-filter.js";
import { extractVideoId } from "../utils/extractors.js";
import { formatTimestamp } from "../utils/formatters.js";
import {
  TranscriptNotAvailableError,
  TranscriptDisabledError,
  VideoNotFoundError,
} from "../types/youtube.js";

const fetcher = new TranscriptFetcher();

async function formatTranscriptError(
  error: unknown,
  videoId: string
): Promise<string> {
  if (error instanceof TranscriptNotAvailableError) {
    try {
      const langs = await fetcher.listAvailableLanguages(videoId);
      if (langs.length > 0) {
        const available = langs
          .map((l) => `${l.code} (${l.name}${l.isAutoGenerated ? ", auto" : ""})`)
          .join(", ");
        return `No captions found for this video. Available languages: ${available}`;
      }
    } catch {
      // ignore secondary errors
    }
    return `This video has no captions available.`;
  }
  if (error instanceof TranscriptDisabledError) {
    return `Captions are disabled for this video.`;
  }
  if (error instanceof VideoNotFoundError) {
    return `Video not found or unavailable: ${videoId}`;
  }
  return `Error: ${error instanceof Error ? error.message : String(error)}`;
}

export function registerTranscriptTools(server: McpServer): void {
  // --- get_transcript ---
  server.registerTool(
    "get_transcript",
    {
      title: "Get Transcript",
      description:
        "Retrieve the full transcript/captions for a YouTube video. " +
        "Does not require an API key. Supports language selection and optional ad filtering via chapter markers.",
      inputSchema: {
        video_id: z.string().describe("Video ID or YouTube URL"),
        include_timestamps: z
          .boolean()
          .default(false)
          .describe("Prefix each segment with [M:SS] timestamps"),
        lang: z
          .string()
          .default("en")
          .describe("Preferred language code (e.g., 'en', 'es', 'ko')"),
        remove_ads: z
          .boolean()
          .default(false)
          .describe(
            "Attempt to filter sponsorships/ads using chapter markers (heuristic, requires chapters)"
          ),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    async ({ video_id, include_timestamps, lang, remove_ads }) => {
      let id: string;
      try {
        id = extractVideoId(video_id);
      } catch (error: unknown) {
        return {
          content: [
            {
              type: "text" as const,
              text: `Error: ${error instanceof Error ? error.message : String(error)}`,
            },
          ],
          isError: true,
        };
      }

      try {
        const result = await fetcher.fetch(id, { lang });
        let segments = result.segments;
        let adNote = "";

        if (remove_ads) {
          const chapters = await fetcher.getChapters(id);
          if (chapters.length > 0) {
            const { filtered, removedChapters } = filterAdSegments(
              segments,
              chapters
            );
            segments = filtered;
            if (removedChapters.length > 0) {
              adNote =
                `\n\n[Note: Filtered ${removedChapters.length} section(s) based on chapter markers: ${removedChapters.join(", ")}. ` +
                `This filtering is heuristic and may not be 100% accurate.]`;
            }
          }
        }

        let text: string;
        if (include_timestamps) {
          text = segments
            .map((s) => `[${formatTimestamp(s.start)}] ${s.text}`)
            .join("\n");
        } else {
          text = segments.map((s) => s.text).join(" ");
        }

        const meta = [
          `Language: ${result.languageCode}${result.isAutoGenerated ? " (auto-generated)" : ""}`,
          `Segments: ${segments.length}`,
        ].join(" | ");

        return {
          content: [
            {
              type: "text" as const,
              text: `*${meta}*\n\n${text}${adNote}`,
            },
          ],
        };
      } catch (error: unknown) {
        const msg = await formatTranscriptError(error, id);
        return {
          content: [{ type: "text" as const, text: msg }],
          isError: true,
        };
      }
    }
  );

  // --- search_transcript ---
  server.registerTool(
    "search_transcript",
    {
      title: "Search Transcript",
      description:
        "Search within a video's transcript for specific content. " +
        "Returns matching segments with surrounding context and timestamps.",
      inputSchema: {
        video_id: z.string().describe("Video ID or YouTube URL"),
        query: z
          .string()
          .min(1)
          .describe("Text to search for within the transcript"),
        context_lines: z
          .number()
          .int()
          .min(0)
          .max(10)
          .default(2)
          .describe("Number of surrounding segments to include for context"),
        lang: z
          .string()
          .default("en")
          .describe("Preferred transcript language"),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    async ({ video_id, query, context_lines, lang }) => {
      let id: string;
      try {
        id = extractVideoId(video_id);
      } catch (error: unknown) {
        return {
          content: [
            {
              type: "text" as const,
              text: `Error: ${error instanceof Error ? error.message : String(error)}`,
            },
          ],
          isError: true,
        };
      }

      try {
        const result = await fetcher.fetch(id, { lang });
        const segments = result.segments;
        const lowerQuery = query.toLowerCase();

        const matchIndices: number[] = [];
        for (let i = 0; i < segments.length; i++) {
          if (segments[i].text.toLowerCase().includes(lowerQuery)) {
            matchIndices.push(i);
          }
        }

        if (matchIndices.length === 0) {
          return {
            content: [
              {
                type: "text" as const,
                text: `No matches found for "${query}" in the transcript.`,
              },
            ],
          };
        }

        const lines: string[] = [
          `# Transcript Search: "${query}"`,
          "",
          `Found ${matchIndices.length} match(es)`,
          "",
        ];

        for (const idx of matchIndices) {
          const seg = segments[idx];
          lines.push(`## Match at [${formatTimestamp(seg.start)}]`);
          lines.push("");

          // Context before
          const ctxStart = Math.max(0, idx - context_lines);
          if (ctxStart < idx) {
            for (let j = ctxStart; j < idx; j++) {
              lines.push(
                `  [${formatTimestamp(segments[j].start)}] ${segments[j].text}`
              );
            }
          }

          // Match
          lines.push(
            `> **[${formatTimestamp(seg.start)}] ${seg.text}**`
          );

          // Context after
          const ctxEnd = Math.min(segments.length - 1, idx + context_lines);
          if (ctxEnd > idx) {
            for (let j = idx + 1; j <= ctxEnd; j++) {
              lines.push(
                `  [${formatTimestamp(segments[j].start)}] ${segments[j].text}`
              );
            }
          }

          lines.push("");
        }

        return {
          content: [{ type: "text" as const, text: lines.join("\n") }],
        };
      } catch (error: unknown) {
        const msg = await formatTranscriptError(error, id);
        return {
          content: [{ type: "text" as const, text: msg }],
          isError: true,
        };
      }
    }
  );
}
